### ISSUE TITLE
<script> in editor prevents loading SiteConfig in admin area

### ISSUE THREAD

**Issue by kinglozzer** [kevingroeger/codeeditorfield#1]
I was just testing this quickly so I’m not sure if this problem is _just_ in `SiteConfig`, but when I have an active text editor with some HTML / JS content it seems to break `SiteConfigAdmin`. Just adding this is enough to cause it to fail to load for me:

```html
<script type="text/javascript">
console.log('hello');
</script>
```

It’ll save the value and re-load the form, but if I then perform a refresh it won’t finish loading.

What appears to happen is the Silverstripe admin JS gets injected into the `<textarea>` after my script instead of being added to `<body>`. Presumably this is caused by framework looking for a `<script>` tag to inject next to.

Changing this line to `{$Value.ATT}` seems to fix it, as the `<script` is encoded to `&lt;script`:

https://github.com/kevingroeger/codeeditorfield/blob/21f94cb89868dcb21cbba2c947dcfc97345b507c/templates/KevinGroeger/CodeEditorField/Forms/CodeEditorField.ss#L7

I haven’t extensively tested it (or tested it outside SiteConfig) but thought I’d raise it as a possible fix, as it doesn’t appear to cause any issues with loading/saving the value

**Comment by kevingroeger** [comment]
Thanks a ton @kinglozzer !

Sorry for taking so long to fix it, I just released 1.3 which should solve the issue!
